# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(427, 207)
        LoginForm.setMinimumSize(QtCore.QSize(0, 0))
        LoginForm.setMaximumSize(QtCore.QSize(1000, 1000))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(LoginForm)
        self.widget.setStyleSheet("QWidget#widget_top{\n"
"border-image:url(:/md7699.png);\n"
"border-top-left-radius:2px;\n"
"border-top-right-radius:2px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_top_bg_label = QtWidgets.QLabel(self.widget)
        self.login_top_bg_label.setStyleSheet("")
        self.login_top_bg_label.setObjectName("login_top_bg_label")
        self.horizontalLayout_2.addWidget(self.login_top_bg_label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(LoginForm)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.url_pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_pushButton.sizePolicy().hasHeightForWidth())
        self.url_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.url_pushButton.setFont(font)
        self.url_pushButton.setFlat(True)
        self.url_pushButton.setObjectName("url_pushButton")
        self.horizontalLayout.addWidget(self.url_pushButton, 0, QtCore.Qt.AlignBottom)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.username_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit{\n"
"background:Transparent;\n"
"border-width:1px;\n"
"border-radius:0px;\n"
"font-size:11pt;\n"
"color:black;\n"
"border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:hover{\n"
"border-width:1px;\n"
"border-radius:0px;\n"
"font-size:11pt;\n"
"color:black;\n"
"border-bottom:1px solid rgb(70,200,50);\n"
"}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout_2.addWidget(self.username_lineEdit, 0, 1, 1, 2)
        self.passwd_lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.passwd_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwd_lineEdit.setFont(font)
        self.passwd_lineEdit.setStyleSheet("QLineEdit{\n"
"background:Transparent;\n"
"border-width:1px;\n"
"border-radius:0px;\n"
"font-size:11pt;\n"
"color:black;\n"
"border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:hover{\n"
"border-width:1px;\n"
"border-radius:0px;\n"
"font-size:11pt;\n"
"color:black;\n"
"border-bottom:1px solid rgb(70,200,50);\n"
"}")
        self.passwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.gridLayout_2.addWidget(self.passwd_lineEdit, 2, 1, 1, 2)
        self.remember_passwd_checkBox = QtWidgets.QCheckBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remember_passwd_checkBox.sizePolicy().hasHeightForWidth())
        self.remember_passwd_checkBox.setSizePolicy(sizePolicy)
        self.remember_passwd_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.remember_passwd_checkBox.setFont(font)
        self.remember_passwd_checkBox.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.remember_passwd_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.remember_passwd_checkBox.setObjectName("remember_passwd_checkBox")
        self.gridLayout_2.addWidget(self.remember_passwd_checkBox, 3, 2, 1, 1)
        self.login_pushButton = QtWidgets.QPushButton(self.widget_4)
        self.login_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton.sizePolicy().hasHeightForWidth())
        self.login_pushButton.setSizePolicy(sizePolicy)
        self.login_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.login_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(84,129,189, 0.8);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    spacing: 500px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"")
        self.login_pushButton.setObjectName("login_pushButton")
        self.gridLayout_2.addWidget(self.login_pushButton, 4, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignBottom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.Auto_login_checkBox = QtWidgets.QCheckBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Auto_login_checkBox.sizePolicy().hasHeightForWidth())
        self.Auto_login_checkBox.setSizePolicy(sizePolicy)
        self.Auto_login_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Auto_login_checkBox.setFont(font)
        self.Auto_login_checkBox.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.Auto_login_checkBox.setObjectName("Auto_login_checkBox")
        self.gridLayout_2.addWidget(self.Auto_login_checkBox, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_2.setStretch(0, 7)
        self.horizontalLayout.addWidget(self.widget_3)
        self.config_pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_pushButton.sizePolicy().hasHeightForWidth())
        self.config_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.config_pushButton.setFont(font)
        self.config_pushButton.setFlat(True)
        self.config_pushButton.setObjectName("config_pushButton")
        self.horizontalLayout.addWidget(self.config_pushButton, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 5)

        self.retranslateUi(LoginForm)
        self.url_pushButton.clicked.connect(LoginForm.open_url_link)
        self.login_pushButton.clicked.connect(LoginForm.ckeck_login)
        self.config_pushButton.clicked.connect(LoginForm.open_config_pane)
        self.Auto_login_checkBox.clicked['bool'].connect(LoginForm.auto_login)
        self.remember_passwd_checkBox.clicked['bool'].connect(LoginForm.remember_pwd)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "RSAS登录"))
        self.login_top_bg_label.setText(_translate("LoginForm", "TextLabel"))
        self.url_pushButton.setText(_translate("LoginForm", "网页登录"))
        self.username_lineEdit.setPlaceholderText(_translate("LoginForm", "请输入账号"))
        self.passwd_lineEdit.setPlaceholderText(_translate("LoginForm", "请输入密码"))
        self.remember_passwd_checkBox.setText(_translate("LoginForm", "记住密码"))
        self.login_pushButton.setText(_translate("LoginForm", "登录"))
        self.label_2.setText(_translate("LoginForm", "密码："))
        self.label.setText(_translate("LoginForm", "账号："))
        self.Auto_login_checkBox.setText(_translate("LoginForm", "自动登录"))
        self.config_pushButton.setText(_translate("LoginForm", "配置信息"))
