# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_Form(object):
    def setupUi(self, log_Form):
        log_Form.setObjectName("log_Form")
        log_Form.resize(1027, 708)
        self.gridLayout_2 = QtWidgets.QGridLayout(log_Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(log_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log_tableView = QtWidgets.QTableView(self.widget_2)
        self.log_tableView.setObjectName("log_tableView")
        self.verticalLayout_2.addWidget(self.log_tableView)
        self.verticalLayout_2.setStretch(0, 1)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(log_Form)
        QtCore.QMetaObject.connectSlotsByName(log_Form)

    def retranslateUi(self, log_Form):
        _translate = QtCore.QCoreApplication.translate
        log_Form.setWindowTitle(_translate("log_Form", "Form"))
