# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasklist_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tasklist_Form(object):
    def setupUi(self, tasklist_Form):
        tasklist_Form.setObjectName("tasklist_Form")
        tasklist_Form.resize(986, 792)
        self.gridLayout_3 = QtWidgets.QGridLayout(tasklist_Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(tasklist_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_list_tableView = QtWidgets.QTableView(self.widget_2)
        self.task_list_tableView.setObjectName("task_list_tableView")
        self.verticalLayout_2.addWidget(self.task_list_tableView)
        self.verticalLayout_2.setStretch(0, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(tasklist_Form)
        QtCore.QMetaObject.connectSlotsByName(tasklist_Form)

    def retranslateUi(self, tasklist_Form):
        _translate = QtCore.QCoreApplication.translate
        tasklist_Form.setWindowTitle(_translate("tasklist_Form", "Form"))
